# -*- coding: utf-8 -*-
"""Task-7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SXy-srfLc0dKB060dLoQvb1vSFIQlBiQ
"""

import sqlite3

# Connect and create the DB
conn = sqlite3.connect('sales_data.db')
cursor = conn.cursor()

# Sales table
cursor.execute('''
    CREATE TABLE sales (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        product TEXT,
        quantity INTEGER,
        price REAL
    )
''')

# Insert sample data
data = [
    ('Apple', 10, 1.5),
    ('Banana', 20, 0.5),
    ('Orange', 15, 0.8),
    ('Apple', 5, 1.5),
    ('Banana', 10, 0.5)
]

cursor.executemany('INSERT INTO sales (product, quantity, price) VALUES (?, ?, ?)', data)
conn.commit()
conn.close()

import pandas as pd
import matplotlib.pyplot as plt

# Connect to DB
conn = sqlite3.connect('sales_data.db')

# SQL Query
query = '''
    SELECT product,
           SUM(quantity) AS total_qty,
           SUM(quantity * price) AS revenue
    FROM sales
    GROUP BY product
'''

# Load result into DataFrame
df = pd.read_sql_query(query, conn)

# Print results
print(df)

# Plot bar chart
df.plot(kind='bar', x='product', y='revenue', title='Revenue by Product')
plt.ylabel('Revenue')
plt.tight_layout()
plt.savefig('sales_chart.png')
plt.show()

conn.close()

